CoockingWebsite/CoockingWebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CoockingWebsite.index.urls')),
    path('accounts/', include('CoockingWebsite.accounts.urls')),
    path('posts/', include('CoockingWebsite.posts.urls')),
    path('dashboard/', include('CoockingWebsite.dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoockingWebsite/CoockingWebsite/accounts/models.py
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from CoockingWebsite.accounts.choices import CookingLevelChoices
from CoockingWebsite.accounts.managers import CustomUserManager
from CoockingWebsite.accounts.validators import OnlyLettersValidator


# Create your models here.
class CustomUser(AbstractUser, PermissionsMixin):
    email = models.EmailField(
        unique=True
    )

    is_staff = models.BooleanField(
        default=False,
    )

    is_active = models.BooleanField(
        default=True,
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()


class UserProfile(models.Model):
    user = models.OneToOneField(
        to=CustomUser,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='profile',
    )
    cooking_level = models.CharField(
        max_length=20,
        choices=CookingLevelChoices.choices,
        default=CookingLevelChoices.BEGINNER,
    )

    first_name = models.CharField(
        max_length=30,
        validators=[OnlyLettersValidator()],

    )

    last_name = models.CharField(
        max_length=30,
        validators=[OnlyLettersValidator()],
    )

    favourite_recipes = models.ManyToManyField(
        'posts.Post',
        related_name='favourite_recipes',
        blank=True,
    )

    total_recipes = models.PositiveIntegerField(
        default=0
    )

    profile_image = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True,
    )

CoockingWebsite/templates/profile_detail/delete_profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <h2>Are you sure you want to delete your profile?</h2>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger"
            onclick="return confirm('Are you sure you want to delete your profile?')">Delete Profile</button>
    </form>

{% endblock %}

CoockingWebsite/templates/profile_detail/profile_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/detail.css' %}">
{% endblock %}

{% block content %}
<div class="profile-container">
    <h1>Profile Details</h1>
    <div class="profile-image-container">
        {% if profile.profile_image %}
        <img src="{{ profile.profile_image.url }}" alt="">
        {% else %}
        <img src="{% static 'images/DefaultProfilePicture.jpg' %}" alt="">
        {% endif %}
    </div>

    <div class="profile-details">
        <p><strong>Username:</strong> {{ profile.user.username|capfirst }}</p>
        <p><strong>First Name:</strong> {{ profile.first_name  }}</p>
        <p><strong>Last Name:</strong> {{ profile.last_name }}</p>
        <p><strong>Cooking Level:</strong> {{ profile.cooking_level }}</p>
        <p><strong>Total Recipes:</strong> {{ profile.total_recipes }}</p>
    </div>

    <a href="{% url 'edit_profile' user.pk %}" class="edit-profile-btn">Edit Profile</a>
</div>
{% endblock %}

CoockingWebsite/templates/profile_detail/profile_edit.html
{% extends 'base/base.html' %}
{% load static %}



{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/edit_profile.css' %}">
{% endblock %}
{% block content %}

    <form class="profile-edit-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h2 class="text-center">Edit Profile</h2>

    <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">First Name</label>
        {{ form.first_name }}
        {{ form.first_name.errors }}
    </div>

    <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">Last Name</label>
        {{ form.last_name }}
        {{ form.last_name.errors }}
    </div>

    <div class="form-group">
        <label for="{{ form.total_recipes.id_for_label }}">Total Recipes</label>
        {{ form.total_recipes }}
    </div>

    <div class="form-group">
        <label for="id_profile_image">Profile Image</label>
        <input type="file" name="profile_image" id="id_profile_image" class="form-control">
    </div>

    <div class="form-group">
        <label for="{{ form.cooking_level.id_for_label }}">Cooking Level</label>
        {{ form.cooking_level }}
    </div>

    <!-- Бутон за записване -->
    <button type="submit" class="btn btn-primary">Save Changes</button>

    <!-- Бутон за изтриване на профила -->
        <button class="btn btn-danger">
    <a href="{% url 'delete_profile' user.pk %}" >Delete Profile</a>
            </button>
</form>

{% endblock %}