CoockingWebsite/CoockingWebsite/posts/urls.py
from django.urls import path, include

from CoockingWebsite.posts import views
from CoockingWebsite.posts.views import AddPost, DeletePost, MyRecipesView, EditPost, DetailPost

urlpatterns = [
    path('add/', AddPost.as_view(), name='add_post'),
    path('my_recipes/', MyRecipesView.as_view(), name='my_recipes'),
    path('post/<int:pk>/', include([
        path('delete/', DeletePost.as_view(), name='delete_post'),
        path('edit/', EditPost.as_view(), name='edit_post'),
        path('detail', DetailPost.as_view(), name='detail_post'),
    ])),
    path('<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('recipe/<int:recipe_id>/like/', views.toggle_like, name='toggle_like'),
]

CoockingWebsite/CoockingWebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CoockingWebsite.index.urls')),
    path('accounts/', include('CoockingWebsite.accounts.urls')),
    path('posts/', include('CoockingWebsite.posts.urls')),
    path('dashboard/', include('CoockingWebsite.dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoockingWebsite/CoockingWebsite/posts/models.py
from django.db import models

from CoockingWebsite.accounts.models import CustomUser
from CoockingWebsite.posts.choices import RecipesCategory


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='posts',
    )

    title = models.CharField(
        max_length=50,
    )

    recipes_images = models.ImageField(
        upload_to='recipe_images/',
        null=True,
        blank=True
    )

    ingredients = models.TextField(
        max_length=200,
    )

    description = models.TextField(
        max_length=2000,
    )

    preparation_time = models.CharField(
        max_length=30,
    )

    recipes_categories = models.CharField(
        max_length=50,
        choices=RecipesCategory.choices,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )


class Comment(models.Model):
    user = models.ForeignKey(
        to=CustomUser,
        on_delete=models.CASCADE,
    )

    to_recipes = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
    )

    text = models.TextField(
        max_length=200,
    )

    date_time_of_comment = models.DateTimeField(
        auto_now_add=True
    )


class Like(models.Model):

    user = models.ForeignKey(
        to=CustomUser,
        on_delete=models.CASCADE,

    )

    to_recipes = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE
    )

    class Meta:
        unique_together = ('user', 'to_recipes')

CoockingWebsite/CoockingWebsite/posts/forms.py
from django import forms

from CoockingWebsite.posts.models import Post, Comment


class BasePostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author', 'created_at', 'updated_at']


class PostAddForm(BasePostForm):
    pass


class PostEditForm(BasePostForm):
    pass


class PostDeleteForm(BasePostForm):
    pass


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text',]

        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Add comment...'}),
        }

CoockingWebsite/CoockingWebsite/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, DetailView

from CoockingWebsite.posts.forms import PostAddForm, PostEditForm, CommentForm
from CoockingWebsite.posts.models import Post, Comment, Like


# Create your views here.
class AddPost(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostAddForm
    context_object_name = 'posts'
    template_name = 'posts/add_post.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    success_url = reverse_lazy('my_recipes')

    def delete(self, request, *args, **kwargs):
        post = self.get_object()
        response = super().delete(request, *args, **kwargs)

        user_profile = post.author.profile
        user_profile.total_recipes = post.author.posts.count()
        user_profile.save()
        return response

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class DetailPost(LoginRequiredMixin, DetailView):
    model = Post
    context_object_name = 'recipe'
    template_name = 'posts/detail_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context


class EditPost(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostEditForm
    template_name = 'posts/edit_post.html'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

    def get_success_url(self):
        return reverse_lazy('my_recipes')


class MyRecipesView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/my_recipes.html'
    context_object_name = 'my_recipes'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        text = request.POST.get('text')

        comment = Comment(text=text, to_recipes=post, user=request.user)

        comment.save()

        return redirect('detail_post', pk=post.id)

    return render(request, 'posts/detail_post.html', {'post': post})


@login_required
def toggle_like(request, recipe_id):
    recipe = get_object_or_404(Post, pk=recipe_id)
    liked_object = Like.objects.filter(to_recipes=recipe, user=request.user).first()

    if liked_object:
        liked_object.delete()
    else:
        Like.objects.create(to_recipes=recipe, user=request.user)

    return redirect(request.META.get('HTTP_REFERER', '/'))

CoockingWebsite/templates/posts/add_post.html
{% extends 'base/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/add_post.css' %}">
{% endblock %}
{% block content %}
<div class="form-container">
<div class="add-post-form">
    <h2>Add New Recipe</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Title -->
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">Title:</label>
            {{ form.title }}
        </div>

        <!-- Ingredients -->
        <div class="form-group">
            <label for="{{ form.ingredients.id_for_label }}">Ingredients:</label>
            {{ form.ingredients }}
        </div>

        <!-- Description -->
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Description:</label>
            {{ form.description }}
        </div>

        <!-- Preparation Time -->
        <div class="form-group">
            <label for="{{ form.preparation_time.id_for_label }}">Preparation Time:</label>
            {{ form.preparation_time }}
        </div>

        <!-- Recipes Categories -->
        <div class="form-group">
            <label for="{{ form.recipes_categories.id_for_label }}">Recipes Categories:</label>
            {{ form.recipes_categories }}
        </div>

        <!-- Recipe Image -->
        <div class="form-group">
            <label for="{{ form.recipes_images.id_for_label }}">Recipe Image:</label>
            {{ form.recipes_images }}
        </div>

        <!-- Add Post Button -->
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
</div>
{% endblock %}

CoockingWebsite/templates/posts/delete_post.html
{% extends "base/base.html" %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/delete_recipe.css' %}">
{% endblock %}

{% block content %}
  <div class="delete-container">
    <h2>Are you sure you want to delete "{{ object.title }}"?</h2>
    <form method="post" class="delete-form">
      {% csrf_token %}
      <button type="submit" class="delete-btn">Yes, delete</button>
      <a href="{% url 'my_recipes' %}" class="cancel-btn">Cancel</a>
    </form>
  </div>
{% endblock %}

CoockingWebsite/templates/posts/detail_post.html
{% extends 'base/base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'styles/detail_post.css' %}">
{% endblock %}

{% block content %}
<main class="container">
    <div class="recipe-detail">
        <!-- Header -->
        <div class="recipe-header">
            {% if recipe.author.profile.profile_image %}
                <img class="profile-image" src="{{ recipe.author.profile.profile_image.url }}" alt="">
            {% else %}
                <img class="profile-image" src="{% static 'images/DefaultProfilePicture.jpg' %}" alt="">
            {% endif %}
            <div>
                <h1>{{ recipe.title }}</h1>
                <p>By: {{ recipe.author.username }}</p>
            </div>
        </div>

        <!-- Image -->
        <div class="recipe-image">
            {% if recipe.recipes_images %}
                <img src="{{ recipe.recipes_images.url }}" alt="{{ recipe.title }}">
            {% else %}
                <img src="{% static 'images/recipe-no-image.png' %}" alt="No Image Available">
            {% endif %}
        </div>

        <!-- Recipe Information -->
        <div class="recipe-info">
            <h2>Ingredients</h2>
            <p>{{ recipe.ingredients }}</p>

            <h2>Description</h2>
            <p>{{ recipe.description }}</p>

            <h2>Preparation Time</h2>
            <p>{{ recipe.preparation_time }}</p>

            <h2>Category</h2>
            <p>{{ recipe.get_recipes_categories_display }}</p>
        </div>

        <!-- Comments Section -->
        <div class="comments-section">
            <h2>Comments:</h2>
            <div class="comments-list">
                {% for comment in recipe.comment_set.all %}
                    <div class="comment">
                        <div class="comment-header">
                            <div class="comment-author">
                                {% if comment.user.profile.profile_image %}
                                    <img class="profile-image" src="{{ comment.user.profile.profile_image.url }}" alt="">
                                {% else %}
                                    <img class="profile-image" src="{% static 'images/DefaultProfilePicture.jpg' %}" alt="">
                                {% endif %}
                                <p>{{ comment.author.username }}</p>
                            </div>
                            <p class="comment-date">{{ comment.date_time_of_comment|date:"F j, Y, g:i a" }}</p>
                        </div>
                        <p class="comment-text">{{ comment.text }}</p>
                    </div>
                {% empty %}
                    <br>
                    <p>Be the first to comment</p>
                {% endfor %}
            </div>

            <!-- Add Comment Form -->

            <form class="comment-form" method="POST" action="{% url 'add_comment' recipe.id %}">
                {% csrf_token %}
                {{ comment_form }}
                <button type="submit">Submit</button>
            </form>
        </div>

        <!-- Footer -->
        <div class="recipe-footer">
            <p>Published on: {{ recipe.created_at|date:"F j, Y" }}</p>
            <p>Last updated: {{ recipe.updated_at|date:"F j, Y, g:i a" }}</p>
        </div>
    </div>
</main>
{% endblock %}

CoockingWebsite/templates/posts/edit_post.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Edit Recipe</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

CoockingWebsite/templates/posts/my_recipes.html
{% extends 'base/base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
{% endblock %}

{% block content %}
    <main class="container">
        <section class="highlight">
            <h1>My recipes</h1>
        </section>
        <section>
            <h2>My latest recipes</h2>
            <section class="recipes">
                <ul>
                    {% for recipe in my_recipes %}
                        <li>
                            {% if recipe.recipes_images %}
                                <a href="{% url 'detail_post' recipe.pk %}">
                                <img  src="{{ recipe.recipes_images.url }}" alt="">
                                </a>
                            {% else %}
                            <img src="{% static 'images/recipe-no-image.png' %}" alt="">
                            {% endif %}
                            <h3>{{ recipe.title }}</h3>
                            <p>{{ recipe.description|slice:":30" }}...</p>
                            <a href="{% url 'edit_post' recipe.pk %}">Edit</a> |
                            <a href="{% url 'delete_post' recipe.pk %}">Delete</a>
                        </li>
                    {% empty %}
                        <li>No recipes available.</li>
                    {% endfor %}
                </ul>
            </section>
        </section>
    </main>
{% endblock %}